### ISSUE TITLE
Confused by a paragraph in 'WebGL and Alpha'

### ISSUE THREAD

**Issue by tuzz** [gfxfundamentals/webgl-fundamentals#268]
Would it be possible to clarify this paragraph?

>Be aware that most if not all Canvas 2D implementations work with pre-multiplied alpha. That means when you transfer them to WebGL and UNPACK_PREMULTIPLY_ALPHA_WEBGL is false WebGL will convert them back to un-premultipiled.

(https://webglfundamentals.org/webgl/lessons/webgl-and-alpha.html)

I think it's trying to say that if `UNPACK_PREMULTIPLY_ALPHA_WEBGL` is true (not false) then WebGL will reverse the pre-multiplication operation on the output of `gl_FragColor` before drawing on the canvas, by dividing through by the alpha channel. Is that right?

Thanks

**Edit:** For a real-world example where this matters, I'm re-mapping RGBA channels in my fragment shader with a 4x4 matrix, but I'm setting `UNPACK_PREMULTIPLY_ALPHA_WEBGL` to true, which results in incorrect output unless I undo this operation and re-do after applying the mapping:

```glsl
// Recover the RGB channels before alpha pre-multiplication.
vec4 color = texture2D(u_texture, v_texcoord);
color.rgb /= color.a;

// Multiply the original color by the 4x4 color mapping matrix.
vec4 mapped = v_color_map * color;
mapped.rgb *= mapped.a;

gl_FragColor = mapped;
```

This probably isn't very efficient (and I probably need a guard for if alpha is zero) but it seems to have the desired effect with a matrix like the following that reduces the opacity by half.

```
1 0 0 0
0 1 0 0
0 0 1 0
0 0 0 0.5
```

I don't suppose there's some other flag I can set so I don't have to re-multiply by alpha again? It seems like two behaviours have been unnecessarily coupled in the WebGL specification:

1) Pre-multiply by alpha when data is fed to the GPU
2) Un-pre-multiply by alpha when data is fed back to the CPU

**Comment by greggman** [comment]
The `UNPACK_PREMULTIPLY_ALPHA_WEBGL` and all the `UNPACK_` settings only affect what happens when you call `texImage2D` (the `texSubImage2D`). They affect how the data is converted as it's being uploaded to the GPU. They do not affect `gl_FragColor` or anything else.

So, if you have a 1x1 pixel 2D canvas. then

```
ctx.fillStyle = `rgba(255, 192, 128, 0.5)`;
ctx.fillRect(0, 0, 1, 1);
```

The data in that one pixel will be [127, 96, 64, 128] (pre-multiplied)

If `UNPACK_PREMULTIPLY_ALPHA_WEBGL` is set to true that data will be uploaded as is (if it's a canvas and the canvas is using`premultipledAlpha: true` which is the default for all canvases). So the data is already premultipled, we're asking for premultipled data, no conversion needed.

If `UNPACK_PREMULTIPLY_ALPHA_WEBGL` is set to false the browser will first do the math to un-premultply those values which will results in [253, 191, 127, 128] (or plus or mins depending on the browser algorithm since the process is lossy)

This is different for images. For images, PNG stores un-premultiplied alpha internally so the same color in a PNG file is [255, 192, 128, 128].

If `UNPACK_PREMULTIPLY_ALPHA_WEBGL` is set to true that data will first be premutlpiled converting it [128, 96, 64, 128] and then that data will be uploaded

If `UNPACK_PREMULTIPLY_ALPHA_WEBGL` is set to false, well the data in a PNG is already un-premulitplied so it will upload as is [255, 192, 128, 128]

**Comment by greggman** [comment]
To put it another way there are 2 settings

1.  Is the source pre-multiplied or un-premultipled
2. Is the UNPACK_PREMULTIPLY_ALPHA_WEBGL true or false

* For Image. Source is always un-premultipled
* for Canvas 2D, Source is always premultiplied
* For WebGL canvas. Source is set at creation time, default is premutiplied but can be changed with {premultipled: false}
* Raw Data in a TypedArray is always considered un-premultiplied

Then at `texImage2D` time if the source premultiplied status matches the `UNPACK_PREMULTIPLY_ALPHA_WEBGL` setting then upload the data as is. If they don't match then do the appropriate conversion first, then upload the data.

**Comment by greggman** [comment]
PS: There is more about WebGL and Alpha in [this article](https://webglfundamentals.org/webgl/lessons/webgl-text-texture.html)

**Comment by tuzz** [comment]
Thanks, that makes sense now! Greatly appreciated.

In my case, I'm still a bit stuck with my color map idea. Ideally, I'd like to avoid having to undo the pre-multiplication step in the fragment shader to multiply the matrix, but that's a separate problem (I asked a question here: https://gamedev.stackexchange.com/questions/181475/how-to-apply-a-color-transform-to-textures-when-using-pre-multiplied-alpha)

I now have a much deeper understanding of the upload data/vertex/fragment shader pipeline and how blend functions work so thanks again! I'll close this now.
