### ISSUE TITLE
Question: way way too much

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#359]
https://webglfundamentals.org/webgl/lessons/webgl-3d-textures.html
![image](https://user-images.githubusercontent.com/20078201/118797428-8a239800-b8d7-11eb-99a5-c950ba82f702.png)

```
That's """way way too much""" to do and """still be fast""".
```

1. Is this a typo or phrase? (`way way too much`)
First time I think this is a typo.
But there is one more same expression in [webgl-text-glyphs](https://webglfundamentals.org/webgl/lessons/webgl-text-glyphs.html).

2. Is it "fast", not "slow"? (`still be fast`)
I think "slow" is more natural.
Because in this context, "there are so many work" -> "so this is slow" -> "so gpu uses mipmap".
Did I get it wrong?

**Comment by greggman** [comment]
I don't think it's wrong.  "way way too xxx" is an expression. You can say "way way way way WAAAAAAAAAAY too much" for example. It's just an expression.

Otherwise the mean is "you can not do that amount of work and still be fast".   Other examples of similar sentences "You have $10. A Burger costs $7 and a drink costs $5 so the total cost would be $12. So you can say "You can not buy a burger and still have enough money for a drink". It's the same pattern. Another way to say it, "That burger costs way too much to still afford to buy a drink"

I guess it's a little awkward but I don't think it's incorrect.

**Comment by TroyTae** [comment]
What a kind explanation!
Thank you :)
