### ISSUE TITLE
Suggestion: How about to use unit square  instead of unit quad?

### ISSUE THREAD

**Issue by TroyTae** [gfxfundamentals/webgl-fundamentals#370]
How about to use unit square instead of unit quad?
Because when I search about `unit quad`, I can get about `Energy unit quad`.
Of course quadrilateral and square are different... 🤔 
https://en.wikipedia.org/wiki/Unit_square

**Comment by greggman** [comment]
I don't feel like "square" is really accurate because it's not a square unless you manipulate it into one by scaling it with extra math. In other words, if you take a unit quad and draw with `gl_Position = position` on a default canvas you'll get a 150x75 rectangle which is not a square.

**Comment by TroyTae** [comment]
Yes it's not square in pixel space.
But doesn't it square in clip space??

**Comment by greggman** [comment]
what size is clip space? To clip space is some arbitrary size. I think it's confusing to call something that doesn't appear to be a square a square.

I don't think of clip space as a square. I think of clip space as the space of the canvas (or whatever we're rendering to). In that space a 0 to 1 by 0 to 1 quad does not appear to be a square.

But I get it's an opinion. if you want to write "unit square" in Korean that's fine by me but I think I prefer unit quad in English since I feel like I'll get questions why it's not appearing as a square

**Comment by TroyTae** [comment]
Ah I understand it.
Actually when I read this sentence:
```
A unit quad is a quad (square) that's 1 unit big.
````
I imagine like this:
![image](https://user-images.githubusercontent.com/20078201/129467102-252ffd1d-353e-4978-a056-1d6d86d01247.png)

So I think it's a square.
But as you told, rendering result can make people confused.
I'll translate it into quadrilateral.
